---
- name: Hello World 
  hosts: jira01
  become: true

  tasks:
    - name: run jira
      docker_container:
        name: jira-01
        image: atlassian/jira-software:{{jiraversion}} 
        state: started
        restart: yes
        network_mode: host
        ports:
         - "8080:8080"
         - "40001:40001"
        volumes: 
          - /data/jira-home:/var/atlassian/application-data/jira
          - /mnt/efs/jira:/var/atlassian/shared
        env:
          EHCACHE_LISTENER_PORT: "40001"
          EHCACHE_LISTENER_HOSTNAME: "10.117.6.239"
          JIRA_NODE_ID: "jira-01"
          JIRA_SHARED_HOME: "/var/atlassian/shared"
          CLUSTERED: "true"
          JVM_MINIMUM_MEMORY: "4096m"
          JVM_MAXIMUM_MEMORY: "4096m"
          ATL_JDBC_URL: "jdbc:postgresql://docker-demo-4.ct9ottbajolw.ap-southeast-2.rds.amazonaws.com:5432/jiradb"
          ATL_JDBC_USER: "postgres"
          ATL_JDBC_PASSWORD: "nqAzWXof3L4kjWG6x7SP"
          ATL_DB_DRIVER: "org.postgresql.Driver"
          ATL_DB_TYPE: "postgres72"
          ATL_PROXY_NAME: "internal-docker-demo-alb-100510385.ap-southeast-2.elb.amazonaws.com"
          ATL_PROXY_PORT: "80"
