---
- name: copy-home
  hosts: jira01 
  become: true

  tasks:
    - name: copy-home
      shell: cp -r /data/jira-home /mnt/efs/jira/home-backup/

- name: Deploy & Start Jira-02
  hosts: jira02
  become: true

  tasks:
    #- name: copy-home-from-efs
    #  shell: cp -r /mnt/efs/jira/home-backup /data/jira-home/
    - name: run jira
      docker_container:
        name: jira-02
        image: atlassian/jira-software:{{jiraversion}} 
        state: started
        restart: yes
        network_mode: host
        ports:
         - "8080:8080"
         - "40001:40001"
        volumes: 
          - /data/jira-home:/var/atlassian/application-data/jira
          - /mnt/efs/jira:/var/atlassian/shared
        env:
          EHCACHE_LISTENER_PORT: "40001"
          EHCACHE_LISTENER_HOSTNAME: "10.117.6.229"
          JIRA_NODE_ID: "jira-02"
          JIRA_SHARED_HOME: "/var/atlassian/shared"
          CLUSTERED: "true"
          JVM_MINIMUM_MEMORY: "2048m"
          JVM_MAXIMUM_MEMORY: "2048m"
          ATL_JDBC_URL: "jdbc:postgresql://jira-docker-demo.ct9ottbajolw.ap-southeast-2.rds.amazonaws.com:5432/jira"
          ATL_JDBC_USER: "postgres"
          ATL_JDBC_PASSWORD: "SuperSecure123"
          ATL_DB_DRIVER: "org.postgresql.Driver"
          ATL_DB_TYPE: "postgres72"
