---
- name: ZDU pipeline start
  hosts: localhost
  #become: true

  tasks:
    - name: trigger ZDU API
      uri:
        url: http://internal-docker-demo-alb-100510385.ap-southeast-2.elb.amazonaws.com/rest/api/2/cluster/zdu/start
        method: POST
        validate_certs: no
        headers:
          Content-Type: application/json
        force_basic_auth: yes
        user: admin
        password: admin
        status_code: 201

- name: upgrade jira01
  hosts: jira01
  become: true

  tasks:
    - name: stop existing container
      docker_container:
        name: jira-01
        state: stopped
    - name: remove jira-01
      docker_container:
        name: jira-01
        state: absent
    - name: run new jira image
      docker_container:
        name: jira-01
        image: atlassian/jira-software:{{jiraversionnew}} 
        state: started
        restart: yes
        network_mode: host
        ports:
         - "8080:8080"
         - "40001:40001"
        volumes: 
          - /data/jira-home:/var/atlassian/application-data/jira
          - /mnt/efs/jira:/var/atlassian/shared
        env:
          EHCACHE_LISTENER_PORT: "40001"
          EHCACHE_LISTENER_HOSTNAME: "10.117.6.239"
          JIRA_NODE_ID: "jira-01"
          JIRA_SHARED_HOME: "/var/atlassian/shared"
          CLUSTERED: "true"
          JVM_MINIMUM_MEMORY: "4096m"
          JVM_MAXIMUM_MEMORY: "4096m"
          ATL_JDBC_URL: "jdbc:postgresql://docker-demo-4.ct9ottbajolw.ap-southeast-2.rds.amazonaws.com:5432/jiradb"
          ATL_JDBC_USER: "postgres"
          ATL_JDBC_PASSWORD: "nqAzWXof3L4kjWG6x7SP"
          ATL_DB_DRIVER: "org.postgresql.Driver"
          ATL_DB_TYPE: "postgres72"
          ATL_PROXY_NAME: "internal-docker-demo-alb-100510385.ap-southeast-2.elb.amazonaws.com"
          ATL_PROXY_PORT: "80"

- name: jira-01-healthplay
  hosts: localhost

  tasks:
    - name: trigger health test
      uri:
        url: http://10.117.6.239:8080/rest/api/2/serverInfo
        method: GET
        validate_certs: no
        headers:
          Content-Type: application/json
        force_basic_auth: yes
        user: admin
        password: admin
        status_code: 200
      register: _result
      until: _result.status == 200
      retries: 720 # 720 * 5 seconds = 1hour (60*60/5)
      delay: 5 # Every 5 seconds

- name: upgrade jira02
  hosts: jira02
  become: true

  tasks:
    - name: stop existing container
      docker_container:
        name: jira-02
        state: stopped
    - name: remove jira-02
      docker_container:
        name: jira-02
        state: absent
    - name: run new jira image
      docker_container:
        name: jira-02
        image: atlassian/jira-software:{{jiraversionnew}} 
        state: started
        restart: yes
        network_mode: host
        ports:
         - "8080:8080"
         - "40001:40001"
        volumes: 
          - /data/jira-home:/var/atlassian/application-data/jira
          - /mnt/efs/jira:/var/atlassian/shared
        env:
          EHCACHE_LISTENER_PORT: "40001"
          EHCACHE_LISTENER_HOSTNAME: "10.117.6.163"
          JIRA_NODE_ID: "jira-02"
          JIRA_SHARED_HOME: "/var/atlassian/shared"
          CLUSTERED: "true"
          JVM_MINIMUM_MEMORY: "4096m"
          JVM_MAXIMUM_MEMORY: "4096m"
          ATL_JDBC_URL: "jdbc:postgresql://docker-demo-4.ct9ottbajolw.ap-southeast-2.rds.amazonaws.com:5432/jiradb"
          ATL_JDBC_USER: "postgres"
          ATL_JDBC_PASSWORD: "nqAzWXof3L4kjWG6x7SP"
          ATL_DB_DRIVER: "org.postgresql.Driver"
          ATL_DB_TYPE: "postgres72"
          ATL_PROXY_NAME: "internal-docker-demo-alb-100510385.ap-southeast-2.elb.amazonaws.com"
          ATL_PROXY_PORT: "80"

- name: jira-02-healthplay
  hosts: localhost

  tasks:
    - name: trigger health test
      uri:
        url: http://10.117.6.163:8080/rest/api/2/serverInfo
        method: GET
        validate_certs: no
        headers:
          Content-Type: application/json
        force_basic_auth: yes
        user: admin
        password: admin
        status_code: 200
      register: _result
      until: _result.status == 200
      retries: 720 # 720 * 5 seconds = 1hour (60*60/5)
      delay: 5 # Every 5 seconds

- name: upgrade jira03
  hosts: jira03
  become: true

  tasks:
    - name: stop existing container
      docker_container:
        name: jira-03
        state: stopped
    - name: remove jira-03
      docker_container:
        name: jira-03
        state: absent
    - name: run new jira image
      docker_container:
        name: jira-03
        image: atlassian/jira-software:{{jiraversionnew}} 
        state: started
        restart: yes
        network_mode: host
        ports:
          - "8080:8080"
          - "40001:40001"
        volumes: 
          - /data/jira-home:/var/atlassian/application-data/jira
          - /mnt/efs/jira:/var/atlassian/shared
        env:
          EHCACHE_LISTENER_PORT: "40001"
          EHCACHE_LISTENER_HOSTNAME: "10.117.6.135"
          JIRA_NODE_ID: "jira-03"
          JIRA_SHARED_HOME: "/var/atlassian/shared"
          CLUSTERED: "true"
          JVM_MINIMUM_MEMORY: "4096m"
          JVM_MAXIMUM_MEMORY: "4096m"
          ATL_JDBC_URL: "jdbc:postgresql://docker-demo-4.ct9ottbajolw.ap-southeast-2.rds.amazonaws.com:5432/jiradb"
          ATL_JDBC_USER: "postgres"
          ATL_JDBC_PASSWORD: "nqAzWXof3L4kjWG6x7SP"
          ATL_DB_DRIVER: "org.postgresql.Driver"
          ATL_DB_TYPE: "postgres72"
          ATL_PROXY_NAME: "internal-docker-demo-alb-100510385.ap-southeast-2.elb.amazonaws.com"
          ATL_PROXY_PORT: "80"

- name: jira-03-healthplay
  hosts: localhost

  tasks:
    - name: trigger health test
      uri:
        url: http://10.117.6.135:8080/rest/api/2/serverInfo
        method: GET
        validate_certs: no
        headers:
          Content-Type: application/json
        force_basic_auth: yes
        user: admin
        password: admin
        status_code: 200
      register: _result
      until: _result.status == 200
      retries: 720 # 720 * 5 seconds = 1hour (60*60/5)
      delay: 5 # Every 5 seconds

#4
- name: upgrade jira04
  hosts: jira04
  become: true

  tasks:
    - name: stop existing container
      docker_container:
        name: jira-04
        state: stopped
    - name: remove jira-04
      docker_container:
        name: jira-03
        state: absent
    - name: run new jira image
      docker_container:
        name: jira-04
        image: atlassian/jira-software:{{jiraversionnew}} 
        state: started
        restart: yes
        network_mode: host
        ports:
          - "8080:8080"
          - "40001:40001"
        volumes: 
          - /data/jira-home:/var/atlassian/application-data/jira
          - /mnt/efs/jira:/var/atlassian/shared
        env:
          EHCACHE_LISTENER_PORT: "40001"
          EHCACHE_LISTENER_HOSTNAME: "10.117.6.169"
          JIRA_NODE_ID: "jira-04"
          JIRA_SHARED_HOME: "/var/atlassian/shared"
          CLUSTERED: "true"
          JVM_MINIMUM_MEMORY: "4096m"
          JVM_MAXIMUM_MEMORY: "4096m"
          ATL_JDBC_URL: "jdbc:postgresql://docker-demo-4.ct9ottbajolw.ap-southeast-2.rds.amazonaws.com:5432/jiradb"
          ATL_JDBC_USER: "postgres"
          ATL_JDBC_PASSWORD: "nqAzWXof3L4kjWG6x7SP"
          ATL_DB_DRIVER: "org.postgresql.Driver"
          ATL_DB_TYPE: "postgres72"
          ATL_PROXY_NAME: "internal-docker-demo-alb-100510385.ap-southeast-2.elb.amazonaws.com"
          ATL_PROXY_PORT: "80"

- name: jira-04-healthplay
  hosts: localhost

  tasks:
    - name: trigger health test
      uri:
        url: http://10.117.6.169:8080/rest/api/2/serverInfo
        method: GET
        validate_certs: no
        headers:
          Content-Type: application/json
        force_basic_auth: yes
        user: admin
        password: admin
        status_code: 200
      register: _result
      until: _result.status == 200
      retries: 720 # 720 * 5 seconds = 1hour (60*60/5)
      delay: 5 # Every 5 seconds

- name: ZDU pipeline complete
  hosts: localhost

  tasks:
    - name: trigger ZDU API
      uri:
        url: http://internal-docker-demo-alb-100510385.ap-southeast-2.elb.amazonaws.com/rest/api/2/cluster/zdu/approve
        method: POST
        validate_certs: no
        headers:
          Content-Type: application/json
        force_basic_auth: yes
        user: admin
        password: admin
        status_code: 200